language: scala

scala:
- 2.12.8

jdk:
- oraclejdk8

before_install:
- git fetch --tags
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.3.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.3

stages:
  - name: format
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


jobs:
  include:
    - stage: format
      script: sbt scalafmt::test
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage +coreJVM/test coverageReport
        - sbt validateScalafmt
        - sbt example/compile
    - stage: release
      script: sbt ci-release



after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi


env:
  matrix:
    secure: joao16F5bwPuDKvMwhZDu3EwZ4PYHY9XMECVTKHSbgaQnzI3D59psjtL4KZnOW3mnbJKI9iIfG8Yr95aR9oGIpfsI9B7k6/yd4/Wd5bvwPqJCZcCB0rQ/DYXMUF400BOgMppQsMps1V2dJgBa155d4ePrZbnK+Qqoi4qzU/+OLhcL6Ibp4AkXtT24j7a1Tz6xluyYv4NISahyxaXpNtO1/vIJjsaKZjZvrFcKZdnHcjXqAIetKJgFnj3SI+cRC6gYIO3ThB2HJb+9chJqIOXNcMHD7aoINlyATg+otDdwcr7LjzRNpFUinp2k+Mc3O0YxUUw3VKUlwseK4NL5mNbbnlvXT52Z3lssqrUM8C5Ka44KUR+9i1jpjVDPdJVUiDiPE9gUJyDktWdpVLh9ZAIdj7CM6NYSVEeTpVV1WgZfaB+Cup0jaHQDpOp8vGcYdJ/xZvwVGr0635qXwjeYyimunytdUXRXNxiQ7DejYroECqSkKBL1jrh63gXQeI/Fw5F+NxHmdTuiJTGn+hET0eCiN78DsqE1bNKBQQnGz04uNkToo5vXJQMX9kjnRAkK7XgGok4ELqotkRYLu2iC2Rl/hxH7+z4oAd8Fhr28Nws9dot5yxTCmC9pLd1rjMt6LkKYuIFjYCJt9BfIXUt+iny4TbujVyLwL7nk6KxBPTEPYg=
